controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_verify_email:
    path: /verify-email
    controller: App\Controller\RegisterController::verifyUserEmail
home:
  path: /
  controller: App\Controller\HomeController::index
